# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  type: LoadBalancer
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
