name: CI/CD Workflow for All Services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  SI_CLUSTER: meditrack-cluster-1
  SI_ZONE: us-central1

jobs:
  build-and-deploy:
    name: Build and Deploy All Services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - patient_service
          - appointment_service
          - notification_service
          - aggregation_service

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js for each service
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Navigate to the specific service directory, install dependencies, and run tests
      - name: Install Dependencies
        working-directory: ${{ matrix.service }}
        run: npm install

      - name: Run Jest Tests
        working-directory: ${{ matrix.service }}
        run: npx jest

      # Set up Google Cloud CLI
      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Authenticate Docker with GKE
      - name: Configure Docker in GKE
        run: gcloud --quiet auth configure-docker

      # Get credentials for GKE cluster
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials "$SI_CLUSTER" --zone "$SI_ZONE"

      # Build Docker image for the service
      - name: Build Docker Image
        working-directory: ${{ matrix.service }}
        run: |
          docker build --tag "gcr.io/$PROJECT_ID/${{ matrix.service }}:prod" .

      # Push Docker image to Google Container Registry
      - name: Push Docker Image to GCR
        run: |
          docker push "gcr.io/$PROJECT_ID/${{ matrix.service }}:prod"

      # Set up Kustomize for deployment
      - name: Set up Kustomize
        run: |
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Install GCloud components for GKE
      - name: Install GCloud Component
        run: gcloud components install gke-gcloud-auth-plugin

      # Deploy the service to the GKE cluster
      - name: Deploy to GKE
        working-directory: ${{ matrix.service }}
        run: |
          ./kustomize edit set image gcr.io/$PROJECT_ID/${{ matrix.service }}:prod=gcr.io/$PROJECT_ID/${{ matrix.service }}:prod
          ./kustomize build . | kubectl apply -f -
          kubectl rollout restart deployment ${{ matrix.service }}
          kubectl get services -o wide
