name: CI/CD Workflow for All Services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  SI_CLUSTER: meditrack-cluster-1
  SI_ZONE: us-central1

jobs:
  build-and-deploy:
    name: Build and Deploy All Services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - patient_service
          - appointment_service
          - notification_service
          - aggregation_service

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js for each service
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Cache node_modules to speed up installation
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Install dependencies
      - name: Install Dependencies
        working-directory: ${{ matrix.service }}
        run: |
          npm install

      # Run npm outdated to check for outdated packages (optional, for logging only)
      - name: Check for Outdated Packages
        working-directory: ${{ matrix.service }}
        run: npm outdated || true

      # Run npm update to update all outdated packages
      - name: Update Outdated Packages
        working-directory: ${{ matrix.service }}
        run: |
          npm update

      # Run npm audit to check for vulnerabilities
      - name: Run npm Audit
        working-directory: ${{ matrix.service }}
        run: |
          npm audit --audit-level=moderate # Fail on moderate or higher vulnerabilities

      # Run Tests
      - name: Run Jest Tests
        working-directory: ${{ matrix.service }}
        run: |
          npx jest --passWithNoTests

      # Set up Google Cloud CLI
      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Authenticate Docker with GKE
      - name: Configure Docker in GKE
        run: gcloud --quiet auth configure-docker

      # Get credentials for GKE cluster
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials "$SI_CLUSTER" --zone "$SI_ZONE"

      # Build Docker image for the service
      - name: Build Docker Image
        working-directory: ${{ matrix.service }}
        run: |
          docker build --tag "gcr.io/$PROJECT_ID/${{ matrix.service }}:prod" .

      # Push Docker image to Google Container Registry
      - name: Push Docker Image to GCR
        run: |
          docker push "gcr.io/$PROJECT_ID/${{ matrix.service }}:prod"

      # Deploy the service to the GKE cluster using kustomization.yml
      - name: Deploy to GKE
        working-directory: ${{ matrix.service }}
        run: |
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
          ./kustomize build . | kubectl apply -f -
          kubectl rollout restart deployment $DEPLOYMENT_NAME
          kubectl get services -o wide
